version: '3.3'

services:
  web:
    image: my.repo:port/image #URI OF IMAGE
    command: gunicorn --config gunicorn_config.py app:application
    ports:
      - "37888:37888"
      #TODO expose ports based on conf.cfg

