version: "3.3"

services:
  web:
    build:
      context: .
    command: hypercorn -b 0.0.0.0:37888 quart_manual_run:application
    ports:
      - "37888:37888"
    environment:
      - IN_PROD=True
    extra_hosts:
      - "host.docker.internal:host-gateway"
